version: '3'

services:
  traefik:
    build:
      context: ./traefik
    ports:
      - 5003:5003
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
  web:
    build:
      context: .
    volumes:
      - .:/app
    command: npm run dev